server:
  port: 8083

spring:
  application:
    name: course-service
  datasource:
    url: jdbc:mysql://localhost:3306/student_management?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

jwt:
  secret: your-secret-key-here-must-be-at-least-32-characters-long
  expiration: 86400000  # 24 hours in milliseconds

logging:
  level:
    org.springframework.security: DEBUG
    com.example.course: DEBUG

# 课程服务特定配置
course:
  max-students-per-class: 30
  min-students-to-start: 5
  max-credits-per-semester: 24
  grading-scale:
    A: 90
    B: 80
    C: 70
    D: 60
    F: 0 
